version: '3'

services:
  weapon:
    build: ./weapon
    image: weapon:0.0.1-SNAPSHOT
    container_name: weapon
    restart: always
    ports:
      - "8081:8080"

  dwarf:
    build: ./dwarf
    image: dwarf:0.0.1-SNAPSHOT
    restart: always
    environment:
      WEAPON_URL: "http://weapon:8080"
    ports:
      - "8082:8080"

  gateway:
    build: ./gateway
    image: gateway:1.0.0-SNAPSHOT
    restart: always
    environment:
      WEAPON_URL: "http://weapon:8080"
      DWARF_URL: "http://dwarf:8080"
      GATEWAY_HOST: "gateway:8080"
    ports:
      - "8084:8080"

  angular:
    build: ./angular
    image: angular:1.0.0-SNAPSHOT
    restart: always
    environment:
      API_URL: http://gateway:8080/drg
    ports:
      - "8087:80"
