GET localhost:8080/drg/weapons
###
//d620af71-586c-4969-a54a-ed35dbc8dc5d engineer
//4c8684cb-25d4-406a-97f7-38b389e921fd shotgun
GET localhost:8080/drg/dwarves
###
GET localhost:8080/drg/dwarves/d620af71-586c-4969-a54a-ed35dbc8dc5d
###
GET localhost:8080/drg/weapons/4c8684cb-25d4-406a-97f7-38b389e921fd

###
PUT localhost:8080/drg/weapons/9eaee866-6eb3-11ea-bc55-0242ac130003
Content-Type: application/json

{
  "name": "Axe",
  "swarmDamage": 3,
  "UUIDdwarf": "d620af71-586c-4969-a54a-ed35dbc8dc5d"
}

###
PATCH http://localhost:8080/drg/weapons/4c8684cb-25d4-406a-97f7-38b389e921fd
Content-Type: application/json

{
"name": "AAAA",
"swarmDamage": 0,
"dwarf":"d620af71-586c-4969-a54a-ed35dbc8dc5d"
}
###
DELETE localhost:8080/drg/weapons/Autocannon
###
GET localhost:8080/drg/weapons
Accept: application/json